#! /usr/bin/env python
# coding: utf-8

import sys

def build(bld):
    bld.shlib(
        target='../beckmancad2',
        source=[
            'BeckmanCAD2ResultReader.cpp',
            'BeckmanCultureActD2.cpp',
        ],
        libpath  =bld.env.libs_shared,
        lib      =bld.env.libs_shared_link,
        use=['includes', 'analyzer', 'serialport', 'common']
    )

    if sys.platform.find('win') < 0:
        bld.env.append_value('CXXFLAGS', '-fPIC');
