#! /usr/bin/env python
# encoding: utf-8

import sys

def build(bld):
    bld.shlib(
        target='../miura300',
        source=[
            'Miura300.cpp',
        ],
        libpath  =bld.env.libs_shared,
        lib      =bld.env.libs_shared_link,
        use=['includes', 'analyzer', 'serialport', 'common', 'protocols']
    )

    if sys.platform.find('win') < 0:
        bld.env.append_value('CXXFLAGS', '-fPIC');
